image: maven:3.8.3-jdk-11

# before_script:
  # - cp $MAVEN_SETTINGS_FILE /builds/feup-tbs/gitlabquestforsofteng/les2122_team_b/feup-cantine/.m2/settings.xml

variables:
  # MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:

deploy:
  stage: deploy
  image: ruby:latest
  script:
      - gem install dpl
      - dpl --provider=heroku --app=$HEROKU_APP_DEPLOY --api-key=$HEROKU_API_KEY
  only:
      - main