image: maven:3.8.3-jdk-11

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  # - cp $MAVEN_SETTINGS_FILE /builds/feup-tbs/gitlabquestforsofteng/les2122_team_b/feup-cantine/.m2/settings.xml
  # Just Another irrelevant change

variables:
  # MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    - master
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - master

deploy:
  stage: deploy
  image: ruby:latest
  script:
      - dpl --provider=heroku --app=feup-food --api-key=$HEROKU_API_KEY
  only:
      - feature/ci_cd