// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RestaurantsverifycodeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void restaurantsverifycode() {
    driver.get("https://feup-food-backoffice.herokuapp.com/auth/login");
    driver.manage().window().setSize(new Dimension(1792, 1056));
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("o");
    driver.findElement(By.id("input-email")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("input-email")).sendKeys("cantinaDeEngenharia@gmail.com");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("password");
    driver.findElement(By.id("input-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".ng-tns-c102-5:nth-child(2)")).click();
    driver.findElement(By.id("input-code")).click();
    driver.findElement(By.id("input-code")).sendKeys("123456789");
    driver.findElement(By.cssSelector(".appearance-filled")).click();
    driver.findElement(By.id("input-code")).click();
    driver.findElement(By.id("input-code")).click();
    {
      WebElement element = driver.findElement(By.id("input-code"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("input-code")).sendKeys("123456789");
    driver.findElement(By.id("input-code")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("input-code")).sendKeys("234567890");
    driver.findElement(By.id("input-code")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".user-name")).click();
    driver.findElement(By.cssSelector(".ng-tns-c102-63 > .menu-title")).click();
  }
}
