// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RestaurantCRUDoperationsassignmentsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void restaurantCRUDoperationsassignments() {
    driver.get("https://feup-food-backoffice.herokuapp.com/auth/login");
    driver.manage().window().setSize(new Dimension(1792, 1056));
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("cantinaDeEngenharia@gmail.com");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("password");
    driver.findElement(By.id("input-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//span[contains(.,\'Assignments\')]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//span[contains(.,\'Assignments\')]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//i")).click();
    driver.findElement(By.name("date")).click();
    driver.findElement(By.name("date")).sendKeys("1999-09-30");
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Dinner']")).click();
    }
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Menu 1']")).click();
    }
    driver.findElement(By.xpath("//ng2-st-actions/a/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to add?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.xpath("//ng2-st-tbody-edit-delete/a/i")).click();
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Lunch']")).click();
    }
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Menu 2']")).click();
    }
    driver.findElement(By.xpath("//ng2-st-tbody-create-cancel/a/i")).click();
    driver.findElement(By.xpath("//a[2]/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".user-picture")).click();
    driver.findElement(By.cssSelector(".ng-tns-c102-61 > .menu-title")).click();
  }
}
