// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RestaurantCRUDoperationsmealTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void restaurantCRUDoperationsmeal() {
    driver.get("https://feup-food-backoffice.herokuapp.com/auth/login");
    driver.manage().window().setSize(new Dimension(1792, 1056));
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("cantinaDeEngenharia@gmail.com");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("password");
    driver.findElement(By.id("input-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//span[contains(.,\'Meals\')]")).click();
    driver.findElement(By.xpath("(//a[contains(@href, \'#\')])[19]")).click();
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(2) > ng2-smart-table-cell .form-control"));
      dropdown.findElement(By.xpath("//option[. = 'Meat']")).click();
    }
    driver.findElement(By.xpath("//input-editor/input")).click();
    driver.findElement(By.xpath("//input-editor/input")).sendKeys("Francesinha");
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("1400 Kcal.");
    driver.findElement(By.xpath("//ng2-st-actions/a/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to add?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.xpath("//ng2-st-tbody-edit-delete/a/i")).click();
    driver.findElement(By.xpath("//input-editor/input")).click();
    driver.findElement(By.xpath("//input-editor/input")).sendKeys("Francesinha (especial com batata)");
    driver.findElement(By.xpath("//ng2-st-tbody-create-cancel/a/i")).click();
    driver.findElement(By.xpath("(//a[contains(@href, \'#\')])[20]")).click();
    driver.findElement(By.xpath("//a[2]/i")).click();
    driver.findElement(By.xpath("//a[2]/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".user-name")).click();
    driver.findElement(By.cssSelector(".ng-tns-c102-61 > .menu-title")).click();
  }
}
