// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RestaurantCRUDoperationsmenusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void restaurantCRUDoperationsmenus() {
    driver.get("https://feup-food-backoffice.herokuapp.com/auth/login");
    driver.manage().window().setSize(new Dimension(1792, 1056));
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("cantinaDeEngenharia@gmail.com");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("password");
    driver.findElement(By.id("input-password")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//span[contains(.,\'Menus\')]")).click();
    driver.findElement(By.xpath("(//a[contains(@href, \'#\')])[26]")).click();
    {
      WebElement element = driver.findElement(By.xpath("(//a[contains(@href, \'#\')])[26]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//input-editor/input")).click();
    driver.findElement(By.xpath("//input-editor/input")).sendKeys("Test menu");
    driver.findElement(By.xpath("//td[3]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[3]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("5");
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[4]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("2");
    driver.findElement(By.xpath("//select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//select"));
      dropdown.findElement(By.xpath("//option[. = 'Pá de porco estufada com ervilhas e arroz de tomate']")).click();
    }
    driver.findElement(By.xpath("//td[6]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[6]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Cavala assada com cebolada e batata cozida']")).click();
    }
    driver.findElement(By.xpath("//td[7]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[7]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Carapau grelhado com arroz']")).click();
    }
    driver.findElement(By.xpath("//td[8]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[8]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Rancho vegan (grão-de-bico, macarrão, couve branca, cenoura)']")).click();
    }
    driver.findElement(By.xpath("//td[9]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select")).click();
    {
      WebElement dropdown = driver.findElement(By.xpath("//td[9]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/select-editor/select"));
      dropdown.findElement(By.xpath("//option[. = 'Mousse de chocolate']")).click();
    }
    driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("None");
    driver.findElement(By.xpath("//td[11]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[11]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("0.50");
    driver.findElement(By.xpath("//ng2-st-actions/a/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to add?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.xpath("//ng2-st-tbody-edit-delete/a/i")).click();
    driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).click();
    {
      WebElement element = driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.xpath("//td[10]/ng2-smart-table-cell/table-cell-edit-mode/div/table-cell-default-editor/div/input-editor/input")).sendKeys("Other information");
    driver.findElement(By.xpath("//ng2-st-tbody-create-cancel/a/i")).click();
    driver.findElement(By.xpath("//a[2]/i")).click();
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to delete?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".context-menu-host .user-name")).click();
    driver.findElement(By.cssSelector(".ng-tns-c102-61 > .menu-title")).click();
  }
}
