// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DashboardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dashboard() {
    driver.get("https://feup-food-client.herokuapp.com/auth/login");
    driver.manage().window().setSize(new Dimension(1920, 1053));
    driver.findElement(By.id("input-email")).sendKeys("francisco@gmail.com");
    driver.findElement(By.id("input-password")).sendKeys("password");
    driver.findElement(By.cssSelector(".appearance-filled")).click();
    assertThat(driver.findElement(By.cssSelector("ngx-summary nb-card-header")).getText(), is("Summary"));
    driver.findElement(By.cssSelector("ngx-intentions nb-card-header")).click();
    assertThat(driver.findElement(By.cssSelector("ngx-intentions nb-card-header")).getText(), is("Intentions"));
    driver.findElement(By.cssSelector(".user-name")).click();
    driver.findElement(By.cssSelector(".ng-tns-c98-5 > .menu-title")).click();
  }
}
